'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Pws0028
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="INTERFAZ LISA", ConfigurationName:="Pws0028.Pws0028SoapPort")>  _
    Public Interface Pws0028SoapPort
        
        'CODEGEN: Generating message contract since the wrapper name (Pws0028.Execute) of message ExecuteRequest does not match the default value (Execute)
        <System.ServiceModel.OperationContractAttribute(Action:="INTERFAZ LISAaction/APWS0028.Execute", ReplyAction:="*")>  _
        Function Execute(ByVal request As Pws0028.ExecuteRequest) As Pws0028.ExecuteResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Pws0028.Execute", WrapperNamespace:="INTERFAZ LISA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Pws0028.ExecuteResponse", WrapperNamespace:="INTERFAZ LISA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="INTERFAZ LISA", Order:=0)>  _
        Public Xmlfin As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Xmlfin As String)
            MyBase.New
            Me.Xmlfin = Xmlfin
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface Pws0028SoapPortChannel
        Inherits Pws0028.Pws0028SoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class Pws0028SoapPortClient
        Inherits System.ServiceModel.ClientBase(Of Pws0028.Pws0028SoapPort)
        Implements Pws0028.Pws0028SoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Pws0028_Pws0028SoapPort_Execute(ByVal request As Pws0028.ExecuteRequest) As Pws0028.ExecuteResponse Implements Pws0028.Pws0028SoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute() As String
            Dim inValue As Pws0028.ExecuteRequest = New Pws0028.ExecuteRequest
            Dim retVal As Pws0028.ExecuteResponse = CType(Me,Pws0028.Pws0028SoapPort).Execute(inValue)
            Return retVal.Xmlfin
        End Function
    End Class
End Namespace
