'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0008")>  _
        Public ReadOnly Property pos_Steward_apws0008_Pws0008() As String
            Get
                Return CType(Me("pos_Steward_apws0008_Pws0008"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0045")>  _
        Public ReadOnly Property pos_Steward_apws0045_Pws0045() As String
            Get
                Return CType(Me("pos_Steward_apws0045_Pws0045"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0007")>  _
        Public ReadOnly Property pos_Steward_apws0007_Pws0007() As String
            Get
                Return CType(Me("pos_Steward_apws0007_Pws0007"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0032")>  _
        Public ReadOnly Property pos_Steward_apws0032_Pws0032() As String
            Get
                Return CType(Me("pos_Steward_apws0032_Pws0032"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0029")>  _
        Public ReadOnly Property pos_Steward_apws0029_Pws0029() As String
            Get
                Return CType(Me("pos_Steward_apws0029_Pws0029"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0006")>  _
        Public ReadOnly Property pos_Steward_apws0006_Pws0006() As String
            Get
                Return CType(Me("pos_Steward_apws0006_Pws0006"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0039")>  _
        Public ReadOnly Property pos_Steward_apws0039_Pws0039() As String
            Get
                Return CType(Me("pos_Steward_apws0039_Pws0039"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0042")>  _
        Public ReadOnly Property pos_Steward_apws0042_Pws0042() As String
            Get
                Return CType(Me("pos_Steward_apws0042_Pws0042"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0047")>  _
        Public ReadOnly Property pos_Steward_apws0047_Pws0047() As String
            Get
                Return CType(Me("pos_Steward_apws0047_Pws0047"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0031")>  _
        Public ReadOnly Property pos_Steward_apws0031_Pws0031() As String
            Get
                Return CType(Me("pos_Steward_apws0031_Pws0031"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0028")>  _
        Public ReadOnly Property pos_Steward_apws0028_Pws0028() As String
            Get
                Return CType(Me("pos_Steward_apws0028_Pws0028"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0033")>  _
        Public ReadOnly Property pos_Steward_apws0033_Pws0033() As String
            Get
                Return CType(Me("pos_Steward_apws0033_Pws0033"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0044")>  _
        Public ReadOnly Property pos_Steward_apws0044_Pws0044() As String
            Get
                Return CType(Me("pos_Steward_apws0044_Pws0044"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0043")>  _
        Public ReadOnly Property pos_Steward_apws0043_Pws0043() As String
            Get
                Return CType(Me("pos_Steward_apws0043_Pws0043"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0046")>  _
        Public ReadOnly Property pos_Steward_apws0046_Pws0046() As String
            Get
                Return CType(Me("pos_Steward_apws0046_Pws0046"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0049")>  _
        Public ReadOnly Property pos_Steward_apws0049_Pws0049() As String
            Get
                Return CType(Me("pos_Steward_apws0049_Pws0049"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0030")>  _
        Public ReadOnly Property pos_Steward_apws0030_Pws0030() As String
            Get
                Return CType(Me("pos_Steward_apws0030_Pws0030"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0034")>  _
        Public ReadOnly Property pos_Steward_apws0034_Pws0034() As String
            Get
                Return CType(Me("pos_Steward_apws0034_Pws0034"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0014")>  _
        Public ReadOnly Property pos_Steward_Pws0014_Pws0014() As String
            Get
                Return CType(Me("pos_Steward_Pws0014_Pws0014"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0041")>  _
        Public ReadOnly Property pos_Steward_apws0041_Pws0041() As String
            Get
                Return CType(Me("pos_Steward_apws0041_Pws0041"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230:8090/lisainterfazsqln/servlet/apws0051")>  _
        Public ReadOnly Property pos_Steward_apws0051_Pws0051() As String
            Get
                Return CType(Me("pos_Steward_apws0051_Pws0051"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.steward.cl/ws_web/Service1.asmx")>  _
        Public ReadOnly Property pos_Steward_Ws_Alumnos_Service1() As String
            Get
                Return CType(Me("pos_Steward_Ws_Alumnos_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0006")>  _
        Public ReadOnly Property Pos2__apws0006_Pws0006() As String
            Get
                Return CType(Me("Pos2__apws0006_Pws0006"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0007")>  _
        Public ReadOnly Property Pos2__apws0007_Pws0007() As String
            Get
                Return CType(Me("Pos2__apws0007_Pws0007"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0008")>  _
        Public ReadOnly Property Pos2__apws0008_Pws0008() As String
            Get
                Return CType(Me("Pos2__apws0008_Pws0008"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0028")>  _
        Public ReadOnly Property Pos2__apws0028_Pws0028() As String
            Get
                Return CType(Me("Pos2__apws0028_Pws0028"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0029")>  _
        Public ReadOnly Property Pos2__apws0029_Pws0029() As String
            Get
                Return CType(Me("Pos2__apws0029_Pws0029"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0030")>  _
        Public ReadOnly Property Pos2__apws0030_Pws0030() As String
            Get
                Return CType(Me("Pos2__apws0030_Pws0030"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/lisainterfazsql2/servlet/apws0032")>  _
        Public ReadOnly Property Pos2__apws0032_Pws0032() As String
            Get
                Return CType(Me("Pos2__apws0032_Pws0032"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0031")>  _
        Public ReadOnly Property Pos2__apws0031_Pws0031() As String
            Get
                Return CType(Me("Pos2__apws0031_Pws0031"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0033")>  _
        Public ReadOnly Property Pos2___apws0033_Pws0033() As String
            Get
                Return CType(Me("Pos2___apws0033_Pws0033"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0034")>  _
        Public ReadOnly Property Pos2__apws0034_Pws0034() As String
            Get
                Return CType(Me("Pos2__apws0034_Pws0034"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0039")>  _
        Public ReadOnly Property Pos2___apws0039_Pws0039() As String
            Get
                Return CType(Me("Pos2___apws0039_Pws0039"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0041")>  _
        Public ReadOnly Property Pos2__apws0041_Pws0041() As String
            Get
                Return CType(Me("Pos2__apws0041_Pws0041"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0042")>  _
        Public ReadOnly Property Pos2__apws0042_Pws0042() As String
            Get
                Return CType(Me("Pos2__apws0042_Pws0042"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0043")>  _
        Public ReadOnly Property Pos2__apws0043_Pws0043() As String
            Get
                Return CType(Me("Pos2__apws0043_Pws0043"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0044")>  _
        Public ReadOnly Property Pos2__apws0044_Pws0044() As String
            Get
                Return CType(Me("Pos2__apws0044_Pws0044"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0045")>  _
        Public ReadOnly Property Pos2__apws0045_Pws0045() As String
            Get
                Return CType(Me("Pos2__apws0045_Pws0045"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0046")>  _
        Public ReadOnly Property Pos2__apws0046_Pws0046() As String
            Get
                Return CType(Me("Pos2__apws0046_Pws0046"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0047")>  _
        Public ReadOnly Property Pos2__apws0047_Pws0047() As String
            Get
                Return CType(Me("Pos2__apws0047_Pws0047"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0048")>  _
        Public ReadOnly Property Pos2_apws00481_Pws0048() As String
            Get
                Return CType(Me("Pos2_apws00481_Pws0048"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/lisainterfazsql2/servlet/apws0049")>  _
        Public ReadOnly Property Pos2__apws0049_Pws0049() As String
            Get
                Return CType(Me("Pos2__apws0049_Pws0049"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0051")>  _
        Public ReadOnly Property Pos2_apws00511_Pws0051() As String
            Get
                Return CType(Me("Pos2_apws00511_Pws0051"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.253:8091/lisainterfazsql2/servlet/apws0014")>  _
        Public ReadOnly Property Pos2_apws00141_Pws0014() As String
            Get
                Return CType(Me("Pos2_apws00141_Pws0014"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/wslisa2/WSLISAERP.asmx")>  _
        Public ReadOnly Property Pos2__WS_LISA_WS_Lisa() As String
            Get
                Return CType(Me("Pos2__WS_LISA_WS_Lisa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230/wslisa/WSLISAERP.asmx")>  _
        Public ReadOnly Property Pos2_ws_lisa_WS_Lisa() As String
            Get
                Return CType(Me("Pos2_ws_lisa_WS_Lisa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.1.230/wspos/pos.asmx")>  _
        Public ReadOnly Property Pos2_ws_pos_POS() As String
            Get
                Return CType(Me("Pos2_ws_pos_POS"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.pos_Steward.My.MySettings
            Get
                Return Global.pos_Steward.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
