'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace wsLisa
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://steward.cl/wservicesLisaERP", ConfigurationName:="wsLisa.WS_LisaSoap")>  _
    Public Interface WS_LisaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaStock", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaStock(ByVal strCodigoEmpresa As String, ByVal strCodigoBodega As String, ByVal strCodigoProducto As String, ByVal fltPorcentajeIncidencia As Single) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaListaPrecio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaListaPrecio(ByVal strCodigoEmpresa As String, ByVal intListaPrecio As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/AgregaDireccion888", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AgregaDireccion888(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/AgregaDireccion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AgregaDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strDireccionDetalle As String, ByVal intCodigoRegion As Integer, ByVal intCodigoCiudad As Integer, ByVal intCodigoComuna As Integer, ByVal intEsDireccionFacturacion As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/AgregaContacto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AgregaContacto( _
                    ByVal strCodigoEmpresa As String,  _
                    ByVal intRutClienteSinDV As Integer,  _
                    ByVal strNombreContacto As String,  _
                    ByVal MBAUXCTOTI As String,  _
                    ByVal intPrefijoTelefonoContacto As Integer,  _
                    ByVal intTelefonoContacto As Integer,  _
                    ByVal intPrefijoTelefonoMovilContacto As Integer,  _
                    ByVal intTelefonoMovilContacto As Integer,  _
                    ByVal intPrefijoFaxContacto As Integer,  _
                    ByVal intFaxContacto As Integer,  _
                    ByVal strMailContacto As String,  _
                    ByVal MBAUXCTOCI As String,  _
                    ByVal intCodigoTelefonicoPais As Integer,  _
                    ByVal intCodigoDireccion As Integer,  _
                    ByVal strRutContactoSinDV As String,  _
                    ByVal strDVContacto As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/AgregaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AgregaCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strDigitoVerificador As String, ByVal strRazonSocial As String, ByVal strNombreFantasia As String, ByVal intCodigoGiro As Integer, ByVal intListaPrecioVenta As Integer, ByVal intListaPrecioArriendo As Integer, ByVal intListaPrecioReposicion As Integer, ByVal strCodigoVendedor As String, ByVal strTipoCliente As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaEstadoPedido", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaEstadoPedido(ByVal strCodigoEmpresa As String, ByVal intFolioLisa As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaEstadoCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaEstadoCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaMontoFleteLisa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaMontoFleteLisa(ByVal strCodigoEmpresa As String, ByVal strXmlListaProductos As String, ByVal intCodigoComunaDespacho As Integer, ByVal strHorarioEntrega As String, ByVal strHorarioRetiro As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaEjecutivoVentas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaEjecutivoVentas(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/UpdateCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function UpdateCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strRazonNombre As String, ByVal intCodigoGiro As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/UpdateDireccion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function UpdateDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoDireccion As Integer, ByVal strDescripcionDireccion As String, ByVal intCodigoRegion As Integer, ByVal intCodigoCiudad As Integer, ByVal intCodigoComuna As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/DeleteDireccion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DeleteDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoDireccion As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/DeleteContacto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DeleteContacto(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoContacto As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/GetCuadroMando", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetCuadroMando() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/ConsultaPos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ConsultaPos(ByVal tipo As String, ByVal empresa As String, ByVal Cliente As String, ByVal sku As String, ByVal cantidad As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/GetVenedores", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetVenedores(ByVal Empresa As String, ByVal Actividad As Char, ByVal codvendedor As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://steward.cl/wservicesLisaERP/AutentificacionWOP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AutentificacionWOP(ByVal Usuario As String, ByVal password As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface WS_LisaSoapChannel
        Inherits wsLisa.WS_LisaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WS_LisaSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsLisa.WS_LisaSoap)
        Implements wsLisa.WS_LisaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ConsultaStock(ByVal strCodigoEmpresa As String, ByVal strCodigoBodega As String, ByVal strCodigoProducto As String, ByVal fltPorcentajeIncidencia As Single) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaStock
            Return MyBase.Channel.ConsultaStock(strCodigoEmpresa, strCodigoBodega, strCodigoProducto, fltPorcentajeIncidencia)
        End Function
        
        Public Function ConsultaListaPrecio(ByVal strCodigoEmpresa As String, ByVal intListaPrecio As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaListaPrecio
            Return MyBase.Channel.ConsultaListaPrecio(strCodigoEmpresa, intListaPrecio)
        End Function
        
        Public Function AgregaDireccion888(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.AgregaDireccion888
            Return MyBase.Channel.AgregaDireccion888(strCodigoEmpresa, intRutClienteSinDV)
        End Function
        
        Public Function AgregaDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strDireccionDetalle As String, ByVal intCodigoRegion As Integer, ByVal intCodigoCiudad As Integer, ByVal intCodigoComuna As Integer, ByVal intEsDireccionFacturacion As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.AgregaDireccion
            Return MyBase.Channel.AgregaDireccion(strCodigoEmpresa, intRutClienteSinDV, strDireccionDetalle, intCodigoRegion, intCodigoCiudad, intCodigoComuna, intEsDireccionFacturacion)
        End Function
        
        Public Function AgregaContacto( _
                    ByVal strCodigoEmpresa As String,  _
                    ByVal intRutClienteSinDV As Integer,  _
                    ByVal strNombreContacto As String,  _
                    ByVal MBAUXCTOTI As String,  _
                    ByVal intPrefijoTelefonoContacto As Integer,  _
                    ByVal intTelefonoContacto As Integer,  _
                    ByVal intPrefijoTelefonoMovilContacto As Integer,  _
                    ByVal intTelefonoMovilContacto As Integer,  _
                    ByVal intPrefijoFaxContacto As Integer,  _
                    ByVal intFaxContacto As Integer,  _
                    ByVal strMailContacto As String,  _
                    ByVal MBAUXCTOCI As String,  _
                    ByVal intCodigoTelefonicoPais As Integer,  _
                    ByVal intCodigoDireccion As Integer,  _
                    ByVal strRutContactoSinDV As String,  _
                    ByVal strDVContacto As String) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.AgregaContacto
            Return MyBase.Channel.AgregaContacto(strCodigoEmpresa, intRutClienteSinDV, strNombreContacto, MBAUXCTOTI, intPrefijoTelefonoContacto, intTelefonoContacto, intPrefijoTelefonoMovilContacto, intTelefonoMovilContacto, intPrefijoFaxContacto, intFaxContacto, strMailContacto, MBAUXCTOCI, intCodigoTelefonicoPais, intCodigoDireccion, strRutContactoSinDV, strDVContacto)
        End Function
        
        Public Function AgregaCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strDigitoVerificador As String, ByVal strRazonSocial As String, ByVal strNombreFantasia As String, ByVal intCodigoGiro As Integer, ByVal intListaPrecioVenta As Integer, ByVal intListaPrecioArriendo As Integer, ByVal intListaPrecioReposicion As Integer, ByVal strCodigoVendedor As String, ByVal strTipoCliente As String) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.AgregaCliente
            Return MyBase.Channel.AgregaCliente(strCodigoEmpresa, intRutClienteSinDV, strDigitoVerificador, strRazonSocial, strNombreFantasia, intCodigoGiro, intListaPrecioVenta, intListaPrecioArriendo, intListaPrecioReposicion, strCodigoVendedor, strTipoCliente)
        End Function
        
        Public Function ConsultaCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaCliente
            Return MyBase.Channel.ConsultaCliente(strCodigoEmpresa, intRutClienteSinDV)
        End Function
        
        Public Function ConsultaEstadoPedido(ByVal strCodigoEmpresa As String, ByVal intFolioLisa As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaEstadoPedido
            Return MyBase.Channel.ConsultaEstadoPedido(strCodigoEmpresa, intFolioLisa)
        End Function
        
        Public Function ConsultaEstadoCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaEstadoCliente
            Return MyBase.Channel.ConsultaEstadoCliente(strCodigoEmpresa, intRutClienteSinDV)
        End Function
        
        Public Function ConsultaMontoFleteLisa(ByVal strCodigoEmpresa As String, ByVal strXmlListaProductos As String, ByVal intCodigoComunaDespacho As Integer, ByVal strHorarioEntrega As String, ByVal strHorarioRetiro As String) As System.Xml.XmlNode Implements wsLisa.WS_LisaSoap.ConsultaMontoFleteLisa
            Return MyBase.Channel.ConsultaMontoFleteLisa(strCodigoEmpresa, strXmlListaProductos, intCodigoComunaDespacho, strHorarioEntrega, strHorarioRetiro)
        End Function
        
        Public Function ConsultaEjecutivoVentas(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer) As System.Data.DataSet Implements wsLisa.WS_LisaSoap.ConsultaEjecutivoVentas
            Return MyBase.Channel.ConsultaEjecutivoVentas(strCodigoEmpresa, intRutClienteSinDV)
        End Function
        
        Public Function UpdateCliente(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal strRazonNombre As String, ByVal intCodigoGiro As Integer) As Boolean Implements wsLisa.WS_LisaSoap.UpdateCliente
            Return MyBase.Channel.UpdateCliente(strCodigoEmpresa, intRutClienteSinDV, strRazonNombre, intCodigoGiro)
        End Function
        
        Public Function UpdateDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoDireccion As Integer, ByVal strDescripcionDireccion As String, ByVal intCodigoRegion As Integer, ByVal intCodigoCiudad As Integer, ByVal intCodigoComuna As Integer) As Boolean Implements wsLisa.WS_LisaSoap.UpdateDireccion
            Return MyBase.Channel.UpdateDireccion(strCodigoEmpresa, intRutClienteSinDV, intCodigoDireccion, strDescripcionDireccion, intCodigoRegion, intCodigoCiudad, intCodigoComuna)
        End Function
        
        Public Function DeleteDireccion(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoDireccion As Integer) As Boolean Implements wsLisa.WS_LisaSoap.DeleteDireccion
            Return MyBase.Channel.DeleteDireccion(strCodigoEmpresa, intRutClienteSinDV, intCodigoDireccion)
        End Function
        
        Public Function DeleteContacto(ByVal strCodigoEmpresa As String, ByVal intRutClienteSinDV As Integer, ByVal intCodigoContacto As Integer) As Boolean Implements wsLisa.WS_LisaSoap.DeleteContacto
            Return MyBase.Channel.DeleteContacto(strCodigoEmpresa, intRutClienteSinDV, intCodigoContacto)
        End Function
        
        Public Function GetCuadroMando() As System.Data.DataSet Implements wsLisa.WS_LisaSoap.GetCuadroMando
            Return MyBase.Channel.GetCuadroMando
        End Function
        
        Public Function ConsultaPos(ByVal tipo As String, ByVal empresa As String, ByVal Cliente As String, ByVal sku As String, ByVal cantidad As Integer) As System.Data.DataSet Implements wsLisa.WS_LisaSoap.ConsultaPos
            Return MyBase.Channel.ConsultaPos(tipo, empresa, Cliente, sku, cantidad)
        End Function
        
        Public Function GetVenedores(ByVal Empresa As String, ByVal Actividad As Char, ByVal codvendedor As String) As System.Data.DataSet Implements wsLisa.WS_LisaSoap.GetVenedores
            Return MyBase.Channel.GetVenedores(Empresa, Actividad, codvendedor)
        End Function
        
        Public Function AutentificacionWOP(ByVal Usuario As String, ByVal password As String) As System.Data.DataSet Implements wsLisa.WS_LisaSoap.AutentificacionWOP
            Return MyBase.Channel.AutentificacionWOP(Usuario, password)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://steward.cl/wservicesLisaERP", ConfigurationName:="wsLisa.WS_LisaHttpGet")>  _
    Public Interface WS_LisaHttpGet
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaStock()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaListaPrecio()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaDireccion888()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaContacto()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEstadoPedido()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEstadoCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaMontoFleteLisa()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEjecutivoVentas()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub UpdateCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub UpdateDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub DeleteDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub DeleteContacto()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub GetCuadroMando()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaPos()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub GetVenedores()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AutentificacionWOP()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface WS_LisaHttpGetChannel
        Inherits wsLisa.WS_LisaHttpGet, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WS_LisaHttpGetClient
        Inherits System.ServiceModel.ClientBase(Of wsLisa.WS_LisaHttpGet)
        Implements wsLisa.WS_LisaHttpGet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub ConsultaStock() Implements wsLisa.WS_LisaHttpGet.ConsultaStock
            MyBase.Channel.ConsultaStock
        End Sub
        
        Public Sub ConsultaListaPrecio() Implements wsLisa.WS_LisaHttpGet.ConsultaListaPrecio
            MyBase.Channel.ConsultaListaPrecio
        End Sub
        
        Public Sub AgregaDireccion888() Implements wsLisa.WS_LisaHttpGet.AgregaDireccion888
            MyBase.Channel.AgregaDireccion888
        End Sub
        
        Public Sub AgregaDireccion() Implements wsLisa.WS_LisaHttpGet.AgregaDireccion
            MyBase.Channel.AgregaDireccion
        End Sub
        
        Public Sub AgregaContacto() Implements wsLisa.WS_LisaHttpGet.AgregaContacto
            MyBase.Channel.AgregaContacto
        End Sub
        
        Public Sub AgregaCliente() Implements wsLisa.WS_LisaHttpGet.AgregaCliente
            MyBase.Channel.AgregaCliente
        End Sub
        
        Public Sub ConsultaCliente() Implements wsLisa.WS_LisaHttpGet.ConsultaCliente
            MyBase.Channel.ConsultaCliente
        End Sub
        
        Public Sub ConsultaEstadoPedido() Implements wsLisa.WS_LisaHttpGet.ConsultaEstadoPedido
            MyBase.Channel.ConsultaEstadoPedido
        End Sub
        
        Public Sub ConsultaEstadoCliente() Implements wsLisa.WS_LisaHttpGet.ConsultaEstadoCliente
            MyBase.Channel.ConsultaEstadoCliente
        End Sub
        
        Public Sub ConsultaMontoFleteLisa() Implements wsLisa.WS_LisaHttpGet.ConsultaMontoFleteLisa
            MyBase.Channel.ConsultaMontoFleteLisa
        End Sub
        
        Public Sub ConsultaEjecutivoVentas() Implements wsLisa.WS_LisaHttpGet.ConsultaEjecutivoVentas
            MyBase.Channel.ConsultaEjecutivoVentas
        End Sub
        
        Public Sub UpdateCliente() Implements wsLisa.WS_LisaHttpGet.UpdateCliente
            MyBase.Channel.UpdateCliente
        End Sub
        
        Public Sub UpdateDireccion() Implements wsLisa.WS_LisaHttpGet.UpdateDireccion
            MyBase.Channel.UpdateDireccion
        End Sub
        
        Public Sub DeleteDireccion() Implements wsLisa.WS_LisaHttpGet.DeleteDireccion
            MyBase.Channel.DeleteDireccion
        End Sub
        
        Public Sub DeleteContacto() Implements wsLisa.WS_LisaHttpGet.DeleteContacto
            MyBase.Channel.DeleteContacto
        End Sub
        
        Public Sub GetCuadroMando() Implements wsLisa.WS_LisaHttpGet.GetCuadroMando
            MyBase.Channel.GetCuadroMando
        End Sub
        
        Public Sub ConsultaPos() Implements wsLisa.WS_LisaHttpGet.ConsultaPos
            MyBase.Channel.ConsultaPos
        End Sub
        
        Public Sub GetVenedores() Implements wsLisa.WS_LisaHttpGet.GetVenedores
            MyBase.Channel.GetVenedores
        End Sub
        
        Public Sub AutentificacionWOP() Implements wsLisa.WS_LisaHttpGet.AutentificacionWOP
            MyBase.Channel.AutentificacionWOP
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://steward.cl/wservicesLisaERP", ConfigurationName:="wsLisa.WS_LisaHttpPost")>  _
    Public Interface WS_LisaHttpPost
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaStock()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaListaPrecio()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaDireccion888()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaContacto()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AgregaCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEstadoPedido()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEstadoCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaMontoFleteLisa()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaEjecutivoVentas()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub UpdateCliente()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub UpdateDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub DeleteDireccion()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub DeleteContacto()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub GetCuadroMando()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub ConsultaPos()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub GetVenedores()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub AutentificacionWOP()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface WS_LisaHttpPostChannel
        Inherits wsLisa.WS_LisaHttpPost, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WS_LisaHttpPostClient
        Inherits System.ServiceModel.ClientBase(Of wsLisa.WS_LisaHttpPost)
        Implements wsLisa.WS_LisaHttpPost
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub ConsultaStock() Implements wsLisa.WS_LisaHttpPost.ConsultaStock
            MyBase.Channel.ConsultaStock
        End Sub
        
        Public Sub ConsultaListaPrecio() Implements wsLisa.WS_LisaHttpPost.ConsultaListaPrecio
            MyBase.Channel.ConsultaListaPrecio
        End Sub
        
        Public Sub AgregaDireccion888() Implements wsLisa.WS_LisaHttpPost.AgregaDireccion888
            MyBase.Channel.AgregaDireccion888
        End Sub
        
        Public Sub AgregaDireccion() Implements wsLisa.WS_LisaHttpPost.AgregaDireccion
            MyBase.Channel.AgregaDireccion
        End Sub
        
        Public Sub AgregaContacto() Implements wsLisa.WS_LisaHttpPost.AgregaContacto
            MyBase.Channel.AgregaContacto
        End Sub
        
        Public Sub AgregaCliente() Implements wsLisa.WS_LisaHttpPost.AgregaCliente
            MyBase.Channel.AgregaCliente
        End Sub
        
        Public Sub ConsultaCliente() Implements wsLisa.WS_LisaHttpPost.ConsultaCliente
            MyBase.Channel.ConsultaCliente
        End Sub
        
        Public Sub ConsultaEstadoPedido() Implements wsLisa.WS_LisaHttpPost.ConsultaEstadoPedido
            MyBase.Channel.ConsultaEstadoPedido
        End Sub
        
        Public Sub ConsultaEstadoCliente() Implements wsLisa.WS_LisaHttpPost.ConsultaEstadoCliente
            MyBase.Channel.ConsultaEstadoCliente
        End Sub
        
        Public Sub ConsultaMontoFleteLisa() Implements wsLisa.WS_LisaHttpPost.ConsultaMontoFleteLisa
            MyBase.Channel.ConsultaMontoFleteLisa
        End Sub
        
        Public Sub ConsultaEjecutivoVentas() Implements wsLisa.WS_LisaHttpPost.ConsultaEjecutivoVentas
            MyBase.Channel.ConsultaEjecutivoVentas
        End Sub
        
        Public Sub UpdateCliente() Implements wsLisa.WS_LisaHttpPost.UpdateCliente
            MyBase.Channel.UpdateCliente
        End Sub
        
        Public Sub UpdateDireccion() Implements wsLisa.WS_LisaHttpPost.UpdateDireccion
            MyBase.Channel.UpdateDireccion
        End Sub
        
        Public Sub DeleteDireccion() Implements wsLisa.WS_LisaHttpPost.DeleteDireccion
            MyBase.Channel.DeleteDireccion
        End Sub
        
        Public Sub DeleteContacto() Implements wsLisa.WS_LisaHttpPost.DeleteContacto
            MyBase.Channel.DeleteContacto
        End Sub
        
        Public Sub GetCuadroMando() Implements wsLisa.WS_LisaHttpPost.GetCuadroMando
            MyBase.Channel.GetCuadroMando
        End Sub
        
        Public Sub ConsultaPos() Implements wsLisa.WS_LisaHttpPost.ConsultaPos
            MyBase.Channel.ConsultaPos
        End Sub
        
        Public Sub GetVenedores() Implements wsLisa.WS_LisaHttpPost.GetVenedores
            MyBase.Channel.GetVenedores
        End Sub
        
        Public Sub AutentificacionWOP() Implements wsLisa.WS_LisaHttpPost.AutentificacionWOP
            MyBase.Channel.AutentificacionWOP
        End Sub
    End Class
End Namespace
